<script>
    import convert from "../convert";
    import hljs from "highlight.js/lib/core";
    import php from "highlight.js/lib/languages/php";
import { Visibility } from "../property";
    hljs.registerLanguage("php",php);
    let visibilities = Object.values(Visibility);
    let json = '{"name":"php","message":[]}';
    let boolOptions = [
        {"key":"getters","desc":"Enable getters"},
        {"key":"arraySerialization","desc":"Array serialization"},
        {"key":"setters","desc":"Enable setters"},
        {"key":"typedMethods","desc":"Type hint methods"},
        {"key":"typedProperties","desc":"Type hint properties"},
        {"key":"includeDeps","desc":"Include class dependencies"},
    ]
    let options = {
        "getters": true,
        "arraySerialization":true,
        "setters":true,
        "typedMethods":true,
        "typedProperties":false,
        "includeDeps":true,
        "namespace":null,
        "className":"AutoGenerated",
        "visibility": Visibility.PROTECTED
    };
    $: code = (function(){
        try{
            return hljs.highlightAuto(convert(json,options)).value;
        }catch(err){
            console.error(err);
            return err.message;
        }
    })();

</script>

<div class="mb-3">
    <div class="row mb-2">
        <div class="col-4">
            <label for="namespace">Namespace</label>
            <input type="text" id="namespace" class='form-control' bind:value={options.namespace}>
        </div>
        <div class="col-4">
            <label for="className">Class name</label>
            <input type="text" id="className" class='form-control' bind:value={options.className}>
        </div>
        <div class="col-4 form-group">
            <label for="visibility">Property visibility</label>
            <select id="visibility"bind:value={options.visibility} class="form-control">
                {#each visibilities as visibility}
                    <option value={visibility}>{visibility}</option>
                {/each}
            </select>

        </div>
    </div>
    <div class="row">
        {#each boolOptions as opt}
            <div class="col-3 mb-2">
                <div class="form-check">
                    <input bind:checked={options[opt.key]} title="{opt.key}" 
                    class="form-check-input" type="checkbox" id="{opt.key}">
                    <label class="form-check-label" for="{opt.key}">
                      {opt.desc}
                    </label>
                  </div>
            </div>
        {/each}
    </div>
</div>

<div class="row">
    <div class="col-5">
        <label for="json" class="form-label"><h5>Json</h5></label>
        <textarea class="form-control w-100" id="json" style="height:80vh" bind:value={json}></textarea>
    </div>
    <div class="col-7">
        <label for="code" class="form-label"><h5>Result</h5></label>
        <div>
            <pre>
                <code class="php">
                    {@html code}
                </code>
            </pre>
        </div>
    </div>
</div>
